### ISSUE TITLE
Live Event wordlist is public

### ISSUE THREAD

**Issue by hyfetch** [JayyDoesDev/christy#7]
So, after looking through some code, i have found that the wordlist used on discord.gg/ntts is public, and located under https://github.com/JayyDoesDev/christy/blob/main/microservice/chatevents.py#L63 and easily accessible,

Solution: delete the wordlist from public repo, or use placeholders in public repository, and other for live repository

**Comment by JayyDoesDev** [comment]
Wasn't expecting people to check it 🤣. Thank you for letting us know, will change the words and put it in our env! -Aris
