### ISSUE TITLE
Live event wordlist is still public 

### ISSUE THREAD

**Issue by Xeravax** [JayyDoesDev/christy#8]
https://github.com/JayyDoesDev/christy/commit/f8be0e0b605c4e1da8d921768ee4a62d832fb8d4 

:)

**Comment by Xeravax** [comment]
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository

**Comment by JayyDoesDev** [comment]
https://github.com/JayyDoesDev/christy/issues/7#issuecomment-1837151757

**Comment by Xeravax** [comment]
True but commit history XD
